# 1. Build stage
FROM golang:1.24 AS builder

WORKDIR /app

# go mod fájlok másolása a cache miatt
COPY go.mod go.sum ./
RUN go mod download

# forráskód bemásolása
COPY . .

# bináris build
RUN go build -o spider-sensor .

# 2. Runtime stage
FROM debian:bookworm-slim

WORKDIR /app

# bináris átmásolása
COPY --from=builder /app/spider-sensor .

# 8080-as port belül
EXPOSE 8080

# futtatás
CMD ["./spider-sensor"]
