services:
  spider-sensor:
    image: pfeiferd01/spider:sensor-arm64
    container_name: spider-sensor
    restart: always
    networks:
      - spider-net
    depends_on:
      - spider-logger
    
  spider-logger:
    image: pfeiferd01/spider:logger-arm64
    container_name: spider-logger
    restart: always
    networks:
      - spider-net
    depends_on:
      - spider-logger-mysql

  spider-light:
    image: pfeiferd01/spider:light-arm64
    container_name: spider-light
    restart: always
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    networks:
      - spider-net
    depends_on:
      - spider-logger

  spider-controller:
    image: pfeiferd01/spider:controller-arm64
    container_name: spider-controller
    devices:
      - "/dev/input/event0:/dev/input/event0"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - spider-net
    depends_on:
      - spider-logger

  spider-nginx:
    image: pfeiferd01/spider:nginx-arm64
    container_name: spider-nginx-proxy
    ports:
      - "9000:9000"
    depends_on:
      - spider-sensor
      - spider-light
      - spider-controller      
    networks:
      - spider-net

  spider-logger-mysql:
    image: mysql:8.1
    container_name: spider-logger-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: spider-logger
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/spider-logger-mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - spider-net

volumes:
  db_data:

networks:
  spider-net:
    driver: bridge