services:
  spider-sensor:
    image: pfeiferd01/spider:sensor-arm64
    container_name: spider-sensor
    restart: always
    networks:
      - spider-net

  spider-light:
    image: pfeiferd01/spider:light-arm64
    container_name: spider-light
    restart: always
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    networks:
      - spider-net

  nginx:
    image: pfeiferd01/spider:nginx-arm64
    container_name: spider-nginx-proxy
    ports:
      - "9000:9000"
    depends_on:
      - spider-sensor
      - spider-light
    networks:
      - spider-net

networks:
  spider-net:
    driver: bridge