# Alap image
FROM python:3.12-slim

# Frissítések és szükséges csomagok telepítése (USB-hoz)
RUN apt-get update && apt-get install -y \
    python3-dev \
    build-essential \
    libudev-dev \
    && rm -rf /var/lib/apt/lists/*

# Munkakönyvtár
WORKDIR /app

# Függőségek telepítése
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Alkalmazás másolása
COPY . .

# Alkalmazás futtatása
CMD ["python", "main.py"]
