FROM python:3.11-slim-bookworm

# Rendszer függőségek telepítése
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential pkg-config \
    libatlas-base-dev libhdf5-dev libhdf5-103 \
    libilmbase-dev libopenexr-dev libgstreamer1.0-dev \
    libcap-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Mappa beállítása
WORKDIR /app

# Python függőségek telepítése
COPY requirements.txt ./
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir picamera2 opencv-python-headless

# Alkalmazás forrásának másolása
COPY . .

# Futtatás
ENV PYTHONUNBUFFERED=1
CMD ["python3", "main.py"]
